### ISSUE TITLE
Number of extractable proofs and matched proofs?

### ISSUE THREAD

**Issue by jizej** [UCSD-PL/proverbot9001#112]
Hi, just for context I am working with @brando90 on an ATP with ML project and we are trying to leverage the coq-projects provided by proverbot for training and testing.

I have built all coq-projects and used `scrape_coq_projects.sh` to extract the proofs. Now I am using `src/count_proofs.py` to check the number of extracted proofs and it reported about 39000 theorems. 

I am wondering what the expected number of extracted theorems should be? I remember from coq-gym that there are 75000 theorems in total, and 39000 seems a bit far from that. 

Thanks in advance.

**Comment by HazardousPeach** [comment]
Hi,

Yeah that does seem a bit low, probably not all your projects built and
scraped properly the first time. It can take a while to get all the
projects to build, they have a variety of setups and issues. What branch
were you using to get the build and scrape scripts? I just updated the
scripts on `master` to match those on my most recent development branch,
which should make some of the project installing better. Beyond that there
can be scrape issues too. Running `get-scrape-failures-coq-project.sh` can
report some of the failing files, and you can run `find coq-projects -name
"*.scrape.partial"` to see any file that started scraping but didn't finish
due to some error. Together those two should get you most of the missing
proofs.

**Comment by jizej** [comment]
Thanks for the immediate reply!

I am using a version of the main branch that's about a month old, and with some minor tweaks to the scripts to fit my environment. 

Thank you for updating the main branch just now. Let me try your new scripts. Will report back once I am done.

**Comment by jizej** [comment]
Hi Alex,

Thank you again for updating the main branch. I figured out the problem was me not noticing `#$(jq -r '.[55:]|.[].project_name' coqgym_projs_splits.json)` skips the first 55 projects. 

So if I scrape from all projects in `coqgym_projs_splits.json` then I am getting **66813** lemmas, and with the '--all' option **22347** lemmas are considered 'matched'.

I have two questions at this point:

1. What does _matched_ mean? If my goal is just to extract proof states and context for all lemmas, do I need to care about this?
2. I noticed that `coqgym_projs_splits.json` includes 124 projects, but there are 135 projects in the `coq-projects` directory. Is there a reason for leaving those projects out of the coqgym splits?

Happy Holidays!

**Comment by HazardousPeach** [comment]
Hey sorry for the slow response,
1. Ah, you mean in the `count_proofs.py` file? So that file has two purposes: to count all the proofs in a file, and also to see how many use only tactics from a particular subset. This uses the context-filter mini-language that proverbot9001 uses to filter data, so you can specify various constraints on the tactics and it'll tell you how many proofs *only* use tactics that meet those constraints. The default context filter it uses looks for proofs with no bullets, semicolons, or background goal selectors. So those are the ones that are showing up as *matched*. So you mostly don't have to worry about which ones are matched. When proofs have semicolons in them, you won't be able to see all the intermediary states, but you can still extract states before and after. And if you want more granular data, you can run  the linearizer to turn most of them into straightline proofs which are "matched".

**Comment by HazardousPeach** [comment]
2. I think it was mostly just because many of the projects were too difficult to get building under semi-modern Coq. We made a lot of effort to make sure all the test projects ran to get a fair comparison, with only one test project we couldn't build. But for training projects we left the ones that were difficult to build because it wouldn't affect the fairness of the comparison.
