### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ApolloLiZhaoyu** [UCSD-PL/proverbot9001#21]
hi, when I install Proverbot on a new machine and run `make setup`, there is a problem:
cd dataloader && rustup run nightly cargo build --release
   Compiling dataloader v0.1.0 (/proverbot9001/dataloader/dataloader-core)
warning: unnecessary braces around method argument
   --> dataloader-core/src/scraped_data.rs:103:18
    |
103 |         obj.init({ TacticContext{relevant_lemmas, prev_tactics, obligation} });
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces
    |
    = note: `#[warn(unused_braces)]` on by default

warning: unnecessary braces around method argument
   --> dataloader-core/src/scraped_data.rs:119:18
    |
119 |         obj.init({ Obligation{hypotheses, goal} });
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces

warning: unnecessary trailing semicolon
   --> dataloader-core/src/scraped_data.rs:264:6
    |
264 |     };
    |      ^ help: remove this semicolon
    |
    = note: `#[warn(redundant_semicolons)]` on by default

warning: unnecessary braces around method argument
   --> dataloader-core/src/scraped_data.rs:529:18
    |
529 |         obj.init({ d });
    |                  ^^^^^ help: remove these braces

warning: unnecessary trailing semicolon
  --> dataloader-core/src/paren_util.rs:85:6
   |
85 |     };
   |      ^ help: remove this semicolon

warning: unused import: `crate::tokenizer::get_symbols`
  --> dataloader-core/src/features.rs:29:5
   |
29 | use crate::tokenizer::get_symbols;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unnecessary braces around method argument
  --> dataloader-core/src/models/goal_enc_evaluator.rs:22:18
   |
22 |         obj.init({ GoalEncMetadata { tokenizer: None } })
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> dataloader-core/src/models/features_polyarg_predictor.rs:652:52
    |
652 |                     let new_hyp_idx = thread_rng().gen_range(0, args.max_premises);
    |                                                    ^^^^^^^^^ -  ----------------- supplied 2 arguments
    |                                                    |
    |                                                    expected 1 argument
    |
note: associated function defined here
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.3/src/rng.rs:127:8
    |
127 |     fn gen_range<T, R>(&mut self, range: R) -> T
    |        ^^^^^^^^^

error: aborting due to previous error; 7 warnings emitted

For more information about this error, try `rustc --explain E0061`.
error: could not compile `dataloader`

To learn more, run the command again with --verbose.
Makefile:118: recipe for target 'src/dataloader.so' failed
make[1]: *** [src/dataloader.so] Error 101
make[1]: Leaving directory '/proverbot9001'
Makefile:36: recipe for target 'setup' failed
make: *** [setup] Error 2

Can you please help me fix this issue?

**Comment by ApolloLiZhaoyu** [comment]
And I note that your results have great results on the CoqGym benchmark, could you please provide the script running for the CoqGym dataset?

**Comment by HazardousPeach** [comment]
For the first issue:

From what I can tell, this appears to be some sort of issue with Rust nightly. On some machines with up-to-date Rust nightly, the gen_range api takes two arguments as endpoints to the range; on others, it takes a range object. My development machine is the former, so the code I have committed uses that, but on many other machines, a patch is required. 

To fix, replace the line in question at line 652:
`let new_hyp_idx = thread_rng().gen_range(0, args.max_premises);`
with
`let new_hyp_idx = thread_rng().gen_range(0..args.max_premises);`
(notice the two periods instead of a comma).

For running on CoqGym:
The proverbot repo has a version of the CoqGym projects installed under `coq_projects`, however, this is the original version include with CoqGym, and many of the projects need to be updated. To run on one of these projects:
1. Check [this page](https://proverbot9001.ucsd.edu/compare/test-projects.html) to see the status of the project.
  a. If the status is "Success" with no qualifiers, you can run on the project without modification
  b. If the status includes "git", you need to clone the project from it's original repo. Googling the project name and "Coq" should find you the repo.
  c. If the status includes a Coq version, switch to that version
  d. If the status includes "b" or "branch", switch to the latest branch (often called "v8.9")
2. Build the project source
  a. Depending on the project, you might have to install dependencies with `opam install --deps-only .` (if there is a .opam file)
  b. If there is a `configure` script, run it.
  c. Finally, run `make -j` (or `make` for single threaded)
3. Scrape the project data
  a. Navigate to the `bench` directory
  b. Run `./get_bench_files.sh` <project-directory>
  c. Run `./scrape_bench.sh <project-directory> -P -j<number-of-threads>`
  d. Leave the `bench` directory
4. Get the weights
  a. The default weights trained on CompCert can be obtained by running `make download-weights`, which will run: `curl -o data/polyarg-weights.dat proverbot9001.ucsd.edu/downloads/weights-10-27-2020.dat`
  b. To reproduce the CoqGym results shown on the website, you'll want to get the CoqGym-trained weights, by running: `curl -o data/polyarg-weights-coqgym.dat proverbot9001.ucsd.edu/downloads/weights-coqgym-2021-02-02.dat`
5. Finally, run the search
  a. Navigate to the `bench` directory
  b. Run `./report_bench <project-directory> coqgym -j<number-of-threads> --include-proof-relevant`
  c. If all goes well, you should see a bunch of progress bars
  d. When they're done, open the file `proverbot9001/search-report/report.html` in a web browser

**Comment by ApolloLiZhaoyu** [comment]
It works, thanks!

**Comment by ApolloLiZhaoyu** [comment]
And when I run `make report`, is it normal to see that:

Problem running statement: 

FAILED: In file ./backend/RTL.v:
(['Answer', 235, 'Completed'],)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/proverbot9001/src/serapi_instance.py", line 584, in run_stmt
    self.update_state()
  File "/proverbot9001/src/serapi_instance.py", line 977, in update_state
    self.cur_state = self.get_next_state()
  File "/proverbot9001/src/serapi_instance.py", line 1000, in get_next_state
    _, lambda x: raise_(BadResponse(msg)))
  File "/.local/lib/python3.7/site-packages/pampy/pampy.py", line 299, in match
    return run(action, lambda_args)
  File "/.local/lib/python3.7/site-packages/pampy/pampy.py", line 48, in run
    return action(*var)
  File "/proverbot9001/src/serapi_instance.py", line 1000, in <lambda>
    _, lambda x: raise_(BadResponse(msg)))
  File "/proverbot9001/src/serapi_instance.py", line 118, in raise_
    raise ex
serapi_instance.BadResponse: [Symbol('Answer'), 235, Symbol('Completed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/proverbot/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "src/scrape.py", line 151, in scrape_file
    raise e
  File "src/scrape.py", line 141, in scrape_file
    process_statement(args, coq, command, f)
  File "src/scrape.py", line 179, in process_statement
    coq.run_stmt(command, timeout=600)
  File "/proverbot9001/src/serapi_instance.py", line 632, in run_stmt
    self.handle_exception(e, stmt)
  File "/proverbot9001/src/serapi_instance.py", line 724, in handle_exception
    _, lambda *args: progn(raise_(UnrecognizedError(args))))
  File "/.local/lib/python3.7/site-packages/pampy/pampy.py", line 299, in match
    return run(action, lambda_args)
  File "/.local/lib/python3.7/site-packages/pampy/pampy.py", line 48, in run
    return action(*var)
  File "/proverbot9001/src/serapi_instance.py", line 724, in <lambda>
    _, lambda *args: progn(raise_(UnrecognizedError(args))))
  File "/proverbot9001/src/serapi_instance.py", line 118, in raise_
    raise ex
serapi_instance.UnrecognizedError: (['Answer', 235, 'Completed'],)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/scrape.py", line 183, in <module>
    main()
  File "src/scrape.py", line 86, in main
    start=1):
  File "/anaconda3/envs/proverbot/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
serapi_instance.UnrecognizedError: (['Answer', 235, 'Completed'],).

**Comment by HazardousPeach** [comment]
Err, yeah, sort of. I haven't seen that particular problem on CompCert, but sometimes the scraper fails the first time around, when it's trying to linearize, but will succeed thereafter. I'm working on a fix on develop, for now, running `make data/compcert-scrape.txt && make data/scrape-test.txt && make report` a second time should fix the problem.

While I have you, do you mind if I ask what you're using Proverbot9001 for? It's always great to get to know how it's being used.

**Comment by ApolloLiZhaoyu** [comment]
Yeah, thanks! I am interested in automated theorem proving, so I want to run some SOTA models to see their performances and compare our methods with them. And it seems like `make search-report` is to prove the whole theorems by DFS, right? But in `search_file.py` main() function has two arguments, but in `proverbot9001.py` line 57, it has only one, so `make search-report` will cause an error, could you help me fix it?

**Comment by HazardousPeach** [comment]
Err, try it now, I think I fixed that problem..

**Comment by HazardousPeach** [comment]
I'm going to assume this is fixed now? But please feel free to open a new issue if needed.
