### ISSUE TITLE
Error Creating Report

### ISSUE THREAD

**Issue by SethPoulsen** [UCSD-PL/proverbot9001#24]
I've followed all the installation instructions, and then when I run `make report` everything runs smoothly until the report generation part, when I get this python error: 

```
Traceback (most recent call last):
  File "./src/proverbot9001.py", line 27, in <module>
    import dynamic_report
  File "/home/seth/git/proverbot9001/src/dynamic_report.py", line 105, in <module>
    def run_prediction(coq : serapi_instance.SerapiInstance, prediction : str) -> Tuple[str,str,Optional[Exception]]:
NameError: name 'serapi_instance' is not defined
make: *** [Makefile:53: report] Error 123
```

I'm running with: 
KDE Neon (Ubunutu 20.04 base)
Python 3.7.10
Opam 2.0.5

Any ideas? Let me know if I can provide more information that would help diagnose the issue. Thanks!

**Comment by HazardousPeach** [comment]
Sorry, that's the "dynamic report" code, which is deprecated. Probably what you actually want is the search report, which you can get with `make search-report`. This does the proof search and reports how many proofs can be found. The old dynamic report was designed to go over each proof state, and make a prediction, and then see if that prediction produces a context identical to the one produced by the "ground truth" command at that state.

But, I think this particular issue has actually been fixed in the dynamic report too, as part of a cleanup pass.
