### ISSUE TITLE
Installing verdi is confusing

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#57]
At one point in the build coqgym deps we have
```
opam install -y coq-verdi
```
since it's bellow the 8.10 switch I assume it requires that switch.

But then the coq proj .json says we want 8.12 and bellow you also install it in the 8.12
```
(cd coq-projects/verdi && opam install -y --ignore-constraints-on=coq .)
```

so which one should I be using?

Also, there is a verdi-raft and I don't see a opam install or other attempts to install it in the deps. Is this a bug? How to proceed?

Error msg:
```
(iit_synthesis) brando9~/proverbot9001 $ opam install -y coq-verdi
[ERROR] Package conflict!
  * Missing dependency:
    - coq >= 8.14
    not available because the package is pinned to version 8.12.2

No solution found, exiting
```

**Comment by brando90** [comment]
what does `opam install -y coq-verdi` stand for?

**Comment by HazardousPeach** [comment]
The `-y` flag is just saying don't ask any questions, just install. I think the issue is that we want verdi on 8.12 for using as a project, but there are also projects that need to be on 8.10 that require verdi, so we end up installing both. verdi-raft isn't installed in the deps because no other project depends on it, so we can just build it in it's local source directory without any installing.
