### ISSUE TITLE
what things need to be "copied" as git submodules and what things are ok just to opam install/pin?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#62]
Basically, why do we need to git submoduling?

**Comment by HazardousPeach** [comment]
We need git submodules for anything we want to actually train or test on,
since we want to the actual Coq .v files to be available in a stable
directory where we can mess with them and add other temp files. But the
projects downloaded in this way also sometimes depend on other Coq
projects, so I was trying to have the dependencies installed through opam
so we don't need manual dependency management where they need to be built
and installed in a particular order.

Given how many breaking changes are happening to the opam packages (that
`global` keyword change really messed things up for backwards
compatibility), that might have actually been the wrong call, and if I were
to set it up now I would just do everything from submodules/clone scripts
and fix a particular commit for each project, so the dependency graph only
needs to be figured out once.
