### ISSUE TITLE
Unable to get coq_serapy

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#76]
I am getting this issue from the git submodule commands:
```
(iit_synthesis) brando9~/proverbot9001 $ git submodule update --init --remote

fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'coq_serapy'
```

suggestions?

**Comment by HazardousPeach** [comment]
The main branch on coq_serapy is called `main`, not `master`. I don't think it was ever called master, since github had already changed their default to `main` when it was created. And I don't see `master` anywhere in the .gitmodules file. So I'm not sure why your copy is trying to find a branch `master`, but that's not the proper branch name.

**Comment by HazardousPeach** [comment]
I'm going to close this, it seems like an individual setup problem.
