### ISSUE TITLE
How to create my own git repo for stable installs of coq-projects?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#83]
I know i have to git fork it. I'm trying this out with cheerios. After that which files do I need to update & run such that 

1. opam installs the right version of my cheerios
2. it uses the right version of coq.

For now I am only updating `coq-cheerios.opam` here: https://github.com/brando90/cheerios/blob/master/coq-cheerios.opam

hopefully this works:
```
opam-version: "2.0"
maintainer: "brandojazz@gmail.com"
version: "dev"

homepage: "https://github.com/brando90/cheerios"
dev-repo: "git+https://github.com/brando90/cheerios.git"
bug-reports: "https://github.com/brando90/cheerios/issues"
license: "BSD-2-Clause"

synopsis: "Coq library for verified serialization"
description: """
A formally verified serialization library for Coq
which defines a typeclass for serializable types and instances
for many standard library types."""

build: [make "-j%{jobs}%"]
install: [make "install"]
depends: [
  "coq" {== "8.16.1"}
  "coq-struct-tact" {= "dev"}
]

tags: [
  "category:Computer Science/Data Types and Data Structures"
  "keyword:serialization"
  "keyword:deserialization"
  "logpath:Cheerios"
]
authors: [
  "Justin Adsuara"
  "Karl Palmskog"
  "Keith Simmons"
  "James R. Wilcox"
  "Doug Woos"
]
```

**Comment by HazardousPeach** [comment]
Hmm no I don't think you need to fork it. You just need to have your Proverbot9001 repo point to the correct existing commits in the cheerios repo. Just forking and modifying the opam file on the master will probably not work, because there are also corresponding changes to the code. Instead, you need to tell proverbot to check out an older version of their code, on an older commit. No forks or branches needed

**Comment by brando90** [comment]
how to freeze a dep chain in opam: https://stackoverflow.com/questions/75452407/how-does-one-pin-freeze-a-version-of-the-dependencies-of-an-opam-project-package#75453430
