### ISSUE TITLE
How to make opam repo add installs stable via a commit?

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#87]
I saw commands like:
```
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
# We don't need it in all opam switches due to incompatabilities: Run `opam repository add <coq-proj> --all-switches|--set-default' to use it in all existing switches, or in newly created switches, respectively. cmd: opam repository add coq-extra-dev --all-switches
opam repo add coq-released https://coq.inria.fr/opam/released
opam repo add psl-opam-repository https://github.com/uds-psl/psl-opam-repository.git
```

would putting the url with the commit work like it does for pin or should I just put the url with commit but use opam pin add?

e.g. as I did for cheerios?
```
opam pin add coq-cheerios git+https://github.com/uwplse/cheerios.git#9c7f66e57b91f706d70afa8ed99d64ed98ab367
```

cross: https://discuss.ocaml.org/t/how-to-make-opam-repo-add-installs-stable-via-a-commit/11433

I want to pin/fix all version so this never breaks again.

**Comment by HazardousPeach** [comment]
`repo add` doesn't have a version, because it's not talking about a particular package. It's saying to add a package registry which points to other packages. For instance, many of the packages in coqgym are not available in the default opam registry, but only in the coq-released registry. But because of that, you don't have to worry about fixing versions on `repo add` commands.
